### ISSUE TITLE
custom animation in SwipePlaceHolderView 

### ISSUE THREAD

**Issue by ericfjl** [janishar/PlaceHolderView#106]
how to define my custom animation when the item view is moving.
I want to make a animation like iOS's UIPushBehavior or UIAttachmentBehavior
this is iOS's github url:https://github.com/summerxx27/XTmomoStyle

https://upload-images.jianshu.io/upload_images/1506501-adc0362731f1ddd5.gif?imageMogr2/auto-orient/strip%7CimageView2/2/w/320

**Comment by janishar** [comment]
@ericfjl Custom animation for SwipePlaceHolderView is not available yet.
