### ISSUE TITLE
i need scroll inside the item

### ISSUE THREAD

**Issue by anshusharma13** [janishar/PlaceHolderView#109]
i think its done by removing  vertical swipe .Please let me know if there is any possiblity to smooth vertical scroll

**Comment by ndwaya** [comment]
Yeah, I am having the same problem. Once setSwipeType is set to 2, scroll works  (but it's very sensitive to touch directions)

**Comment by slum44** [comment]
I was just curious and quickly bashed together a recycler view inside of a swipe view card.  Even when I setSwipeType to horizontal only, I'm not able to scroll vertically within the recyclerview

**Comment by anshusharma13** [comment]
@slum44  if you will find the  solution then let me know please

**Comment by janishar** [comment]
@anshusharma13 @slum44 @ndwaya 
SwipePlaceHoldeView don't have the functionality of using list view inside Cards yet.
