### ISSUE TITLE
update events call upons

### ISSUE THREAD

**Issue by jjhesk** [janishar/PlaceHolderView#11]
just a quick question if the holder support supports late update events in the view holder. 
for example, I got this hierarchy...
PlaceHolderView
.
.
PlaceHolderView
.
.
.
PlaceHolderView
.
.
The Child Holder

Can I possibly update this child with late event with http request?

**Comment by janishar** [comment]
@jjhesk can you provide a little more detail? 
If by late update you mean the the view being updated from the network call after being rendered. Then yes.
In the class use 
"@Position" 
private int position

Then notify in @Resolve annotated method
placeHolderView.getAdapter().notifyItemChanged(position);

**Comment by janishar** [comment]
@jjhesk To streamline the solution I have added few methods to the PlaceHolderView
1. `<T>int getViewResolverPosition(T resolver)`: This will give the position of the class object which is added as the item view, even before the item view is binded to the window.
2. `<T>void refreshView(T resolver)`: This will refresh the item view after new data is added based on the class object reference added as item view.
3. `public void refreshView(int position)`: This will refresh the item view after new data is added based on the position of item view.
4. `void refresh()`: It will re draw the entire PlaceHolderView with new data.

Hope this solves your problem

**Comment by jjhesk** [comment]
im at 0.2.6 @janishar when the new child are added on later event to the placeholder i have got a crash. the reason was that the xml wasnt able to inflate.

**Comment by janishar** [comment]
@jjhesk you should not refer to the view elements other than in method annotated with @Resolve. Because the view may have be removed from the window or not have been bind to the PlaceHolderView. What you should do is, place the view data in a list, use list item based on position to populate the view and update the list and refresh the view . Its the same procedure you would take when using recyclerView.

**Comment by janishar** [comment]
@jjhesk Also you can do is that, update the variables of the class and call refresh. When the view will be bind then it will automatically update the view. Please use 0.2.7

**Comment by janishar** [comment]
@jjhesk This is what I understood the use case. If there is something else that you have implemented please explain a bit in more detail. Thanks

**Comment by jjhesk** [comment]
i found out eventually. it is not the case.  The view from  'com.mikhaellopez:circularimageview:3.0.2' with using `com.mikhaellopez.circularimageview.CircularImageView` . The view was inflated normally not in the placeholderview but it has problem to inflate within placeholderview. Instead I tried to use ImageView, it inflated normally.

**Comment by jjhesk** [comment]
according to your suggestion, should i add `  mProfileList.refresh();` the loaded list is added to the child placeholderview?

**Comment by janishar** [comment]
@jjhesk Do few changes...
1. Make a List<itemProfileCircle>
2. Add new itemProfileCircle(mContext, user_item) in that list.
3. mProfileList.addView don't use outside @Resolve
4. In onResolved()  use
```java
for(itemProfileCircle item : itemProfileCircleList){
      mProfileList.addView(item);
}
```
5. Also in onResolved(), do call mProfileList.removeAllViews() before adding views. Because this will safeguard against repetitive view addition when view is rebinded.

**Comment by jjhesk** [comment]
@janishar at which point should i initiate the item request for the best?

**Comment by janishar** [comment]
@jjhesk you can initiate the item request as soon as the class is constructed. The fetched data will be stored in itemProfileCircleList. When the view is binded to the window it will automatically pick up the fetched data and add the view into the sub placeholdeview. Also do call mainPlaceHoldeView.refresh() (mainPlaceHoldeView is the parent placeholderview containing mProfileList) when the data has been fetched.

**Comment by janishar** [comment]
@jjhesk Also from the optimisation point of view I would suggest one more thing. 
1. Create a class variable  
```java
GridLayoutManager gridLayoutManager
```
2. In constructor, initialize this variable
```java
gridLayoutManager = new GridLayoutManager(mContext, 4, LinearLayoutManager.VERTICAL, false);
```
3. Then use it in onResolved
```java
.setLayoutManager(gridLayoutManager);
```

**Comment by janishar** [comment]
@jjhesk Is this issue solved? if yes then please close this issue. Thanks

**Comment by jjhesk** [comment]
its interesting that i am encounter the issue on #13 relates to this issue. Now I have defined 2 different managers on the constructor and there is an logic decision which layoutmanager to use during resolve process.
1. GridLayoutManager
2. LinearLayoutManager

There are few times i got crashed from calling one of them and it is not consistent. 

java.lang.IllegalStateException: View with id 2131886663: com.mindorks.placeholderview.PlaceHolderView#onMeasure() did not set the measured dimension by calling setMeasuredDimension()

**Comment by jjhesk** [comment]
ok. I got this resolved. These items needs to be check,

```java
   if (mCateListingReference.getAllViewResolvers().size() == 0) {
            if (this.culture_asian) {
                for (itemCateStrAsian str : mAsianShowList) {
                    mCateListingReference.addView(str);
                }
            } else {
                for (itemCateStrWestern str : mWesternShowList) {
                    mCateListingReference.addView(str);
                }
            }
        }
```

**Comment by janishar** [comment]
@jjhesk @NonReusable should be used in view which once removed from the placeholderview is not to be added or modified again.
Do you still need some reference example or you got it solved?

**Comment by jjhesk** [comment]
yes. I need reference for implementation of late events call upon updating the new list.

**Comment by janishar** [comment]
@jjhesk  I will create a repository with the example and post it here in sometime

**Comment by janishar** [comment]
I am closing this thread and moving the discussion to #13

**Comment by rakesh1001** [comment]
how to perform the action on adapterItem from fragment??

**Comment by shiprasinghal1** [comment]
Hello,
I want to update a child in particular parent in different fragment than the fragment where Place Holder view is initialized/populated. I am unable to find any particular method in PlaceHolderView class for same. 
Can you please suggest something. Thanks

**Comment by aakashbhusal7** [comment]
how to get the position of child view. I need to increment the symbol number for list of data from child view.
