### ISSUE TITLE
 AAnnotationProcessor 1.0.2 generate to wrong .java from Kotlin

### ISSUE THREAD

**Issue by van-tran** [janishar/PlaceHolderView#111]
AnnotationProcessor 1.0.2 generate all members as private in .java although they were set as non-internal in kotlin.
Is there any work around for this ?

**Comment by janishar** [comment]
@musicdotexe use `lateinit `
Refer this project for example:
https://github.com/janishar/tutorials/blob/master/tinder-swipe-kotlin/app/src/main/java/tinderswipe/swipe/mindorks/demo/TinderCard.kt
