### ISSUE TITLE
Tinder card view's design changes not affected, place holder view dosen't takes all width it wraps very thin around 60 70 dp

### ISSUE THREAD

**Issue by andiakashd** [janishar/PlaceHolderView#112]
Tinder card view's design changes not affected, place holder view dosen't takes all width it wraps very thin around 60 70 dp,
I have made changes to tinder_card_view, added some extra text views and small images,
m I missing anything or I can not change view,
My layout's root view is contraintLayout, which has  one CardView and one Linear layout under beneath

**Comment by janishar** [comment]
refer this link:
https://github.com/janishar/Tutorials/blob/master/tinder-swipe-v2/app/src/main/java/dependency/greendao/test/tinder/directional/MainActivity.java

See these codes:
```java
    int bottomMargin = Utils.dpToPx(160);
    Point windowSize = Utils.getDisplaySize(getWindowManager());

...
 mSwipeView
    .getBuilder()
    ...
    .setSwipeDecor(new SwipeDecor() 
                        .setViewWidth(windowSize.x)
                        .setViewHeight(windowSize.y - bottomMargin)
```
