### ISSUE TITLE
What was the main reason for going with the annotation based adapting?

### ISSUE THREAD

**Issue by c-b-h** [janishar/PlaceHolderView#115]
Hi,

Looking around various libraries for achieving Tinder-like swipe, I came across your `SwipePlaceHolderView` but the more I look at the code the more I find it cumbersome to integrate with our current architecture. Most other similar libraries use a form of `Adapter`-approach were `View`s are created and bound. This allows developers to pick whatever binding library (ButterKnife, Android Data Binding etc.) they prefer or even opt out of binding altogether.

I am curious of why you decided tying the binding with the usage of your component instead of going with the well-known approach of tying adapters to an adaptable `View`?

Thanks in advance for clarification,
Cyrus

**Comment by janishar** [comment]
SwipePlaceHolderView removes most of the boilerplate code. The main motivation for this kind of approach is to eliminate any external dependency and make is self contained.
For using swipe placeholderview, there are 3 simple steps:
1. Define the item view xml layout
2. Create the class that servers as the itemview holder. 
3. Configure the swipedecor and builder (if needed)

You can find the docs here: 
http://janishar.com/PlaceHolderView/docs/introduction.html

Can you tell me the kind of difficulty you are facing with the integration?
