### ISSUE TITLE
How to find current user id which is show on the first card Position

### ISSUE THREAD

**Issue by NaveenDevrani** [janishar/PlaceHolderView#119]
How to find current user id which is show on the first card Position.....
i try to get but the id  got the 3rd position cardview .... but i want to get the position of  first card which show  currently

**Comment by NaveenDevrani** [comment]
please sir replay me , very fast

**Comment by janishar** [comment]
Refer #120

**Comment by NaveenDevrani** [comment]
@janishar   sir, i need one more  help. sir.....
   it is posible to   create a functionality like tinder ..
 in one  cardview show multiple  image of single  user  and

 when i click the  image or card view   ,i can see all image the  of the
user.....  and also  show the indicator  which show  the no. of image of
the  user same as tinder

ssir i sent a video on mail....   .. i m showing on video  what i exactly
try to saying...
