### ISSUE TITLE
Issue on Callbacks

### ISSUE THREAD

**Issue by mirmibrahim** [janishar/PlaceHolderView#128]
Hello , 
Only cancel callback works if i set the direction to vertical only .While if i change it to default it works.
Kindly look into it because i need only vertical gestures and it shows my no callback. thanks

  dataBiding.swipeView.getBuilder()
                                .setDisplayViewCount(allDeals.size())
                                .setSwipeType(SwipePlaceHolderView.SWIPE_TYPE_VERTICAL)
                                .setIsUndoEnabled(false)
                                .setSwipeVerticalThreshold(Utils.dpToPx(50))
                              .setSwipeHorizontalThreshold(Utils.dpToPx(50))
                                .setHeightSwipeDistFactor(10)
                                .setWidthSwipeDistFactor(5)
                                .setSwipeDecor(new SwipeDecor()
                                        .setViewWidth(windowSize.x)
                                        .setViewHeight(windowSize.y - bottomMargin)
                                        .setViewGravity(Gravity.TOP)
                                        .setPaddingTop(0)
                                        .setSwipeAnimTime(mAnimationDuration)
                                        .setRelativeScale(0.01f)
                                        .setSwipeInMsgLayoutId(R.layout.tinder_swipe_in_msg_view)
                                        .setSwipeOutMsgLayoutId(R.layout.tinder_swipe_out_msg_view));

**Comment by mirmibrahim** [comment]
@janishar Can you help on it . Please

**Comment by janishar** [comment]
@mirmibrahim I find that you are using SwipeDirectionalView in place of SwipePlaceHolderView so you should use this callback: 

```java
@SwipeOutDirectional
public void onSwipeOutDirectional(SwipeDirection direction) {
        Log.d("DEBUG", "SwipeOutDirectional " + direction.name());
        if (direction.getDirection() == SwipeDirection.TOP.getDirection()) {
            mCallback.onSwipeUp();
        }
    }
```
Refer this for complete callback docs: http://janishar.com/PlaceHolderView/docs/sdv-view-definition.html

**Comment by mirmibrahim** [comment]
Yes i am using this callback. But nothing happens. Not even this log shows the log.That is the problem . if the callback was working then everything was fine for me. @janishar

**Comment by janishar** [comment]
Okay I will check and revert back tonight

**Comment by janishar** [comment]
@mirmibrahim Apologies for the wrong answer. The SwipeDirectionalView does not override for Horizontal and Vertical swipe types. You will have to use these callbacks:
```java
    @SwipeIn
    public void onSwipeIn() {
        Log.d("DEBUG", "onSwipedIn");
    }

    @SwipeOut
    public void onSwipeOut() {
        Log.d("DEBUG", "onSwipeOut");
    }
```

**Comment by mirmibrahim** [comment]
it Worked. Thanks
