### ISSUE TITLE
Not getting callback for SWIPE_TYPE_HORIZONTAL...

### ISSUE THREAD

**Issue by RozinaDarediya** [janishar/PlaceHolderView#134]
Hi @janishar 

In my project I have used this framework. I want to allow user to swipe only Left or Right and not Top and Bottom. 

I looked at [#123](https://github.com/janishar/PlaceHolderView/issues/123)  and set
_**.setSwipeType(SwipePlaceHolderView.SWIPE_TYPE_HORIZONTAL);**_ 

And yes it only swipe to left or right but I am not getting any callback (i.e onSwipeInDirectional, onSwipeOutDirectional, SwipingDirection) for that.

I have code as below in Activity:
  mSwipeView.getBuilder()
                        .setDisplayViewCount(2)     //to display no of cards at a time
                        .setIsUndoEnabled(true)
                        .setSwipeVerticalThreshold(Utils.dpToPx(50))
                        .setSwipeHorizontalThreshold(Utils.dpToPx(50))
                        .setHeightSwipeDistFactor(10)
                        .setWidthSwipeDistFactor(5)
                        .setSwipeType(SwipePlaceHolderView.SWIPE_TYPE_HORIZONTAL)
                        .setSwipeDecor(new SwipeDecor()
                                .setViewWidth(windowSize.x)
                                .setViewHeight(windowSize.y - bottomMargin)
                                .setViewGravity(Gravity.TOP)
                                .setPaddingTop(20)
                                .setSwipeAnimTime(mAnimationDuration)
                                .setRelativeScale(0.01f)
                                .setSwipeInMsgLayoutId(R.layout.tinder_swipe_in_msg_view)
                                .setSwipeOutMsgLayoutId(R.layout.tinder_swipe_out_msg_view));

Code of callback in SwipeCard:
 @SwipingDirection
    private void SwipingDirection(SwipeDirection direction){
        Log.e("SwipeOutDirectional " + direction.name());
    }

    @SwipeOutDirectional
    private void onSwipeOutDirectional(SwipeDirection direction) {
        Log.e("SwipeOutDirectional " + direction.name());
    }

    @SwipeInDirectional
    private void onSwipeInDirectional(SwipeDirection direction) {
        Log.e("SwipeInDirectional " + direction.name());
    }

Please I need your guidance.
Hope you will reply soon.
Thank you

**Comment by janishar** [comment]
@RozinaDarediya 
Use these callbacks for only two directions constrained movement:
```java
    @SwipeOut
    public void onSwipedOut() {
        Log.d("DEBUG", "onSwipedOut");
    }

    @SwipeCancelState
    public void onSwipeCancelState() {
        Log.d("DEBUG", "onSwipeCancelState");
    }

    @SwipeIn
    public void onSwipeIn() {
        Log.d("DEBUG", "onSwipedIn");
    }
```
