### ISSUE TITLE
How to expand multiple items on ExpandablePlaceHolderView

### ISSUE THREAD

**Issue by hanming223** [janishar/PlaceHolderView#143]
When I expand an item,  currently expanded item collapses.  How to prevent this?
I want to expand multiple items.

**Comment by janishar** [comment]
@hanming223 remove `@SingleTop`
Refer this: https://janishar.com/PlaceHolderView/docs/ephv-parent.html#docsNav

**Comment by hanming223** [comment]
It works.  Thank you.
