### ISSUE TITLE
@View field is null

### ISSUE THREAD

**Issue by satadii11** [janishar/PlaceHolderView#146]
Hey this is my code

```
@NonReusable
@Layout(R.layout.item_swipe_card)
class TinderCard(
    private val item: Interest
) {
    @View(R.id.sdvItemSwipeCard)
    @JvmField
    var ivInterest: SimpleDraweeView? = null
    @View(R.id.tvItemSwipeCard)
    @JvmField
    var tvInterest: TextView? = null

    var likedListener: (() -> Unit)? = null
    var dislikedListener: (() -> Unit)? = null

    @Resolve
    fun onResolved() {
        ivInterest?.setActualImageResource(item.image)
        tvInterest?.text = item.name
    }

    @SwipeOut
    fun onSwipeOut() {
        dislikedListener?.invoke()
    }

    @SwipeIn
    fun onSwipeIn() {
        likedListener?.invoke()
    }
}
```

There is nothing wrong with this code few hours ago. But now, i don't understand myself the tvInterest is null while the ivInterest is not. Why is that problem occured? How do i solve it? I've tried to make likedListener and dislikedListener to @JvmField, it doesn't work. I've also tried to use lateinit modifier, it make my apps force close.  

Really appreciate your help, thanks

**Comment by thanhpd-teko** [comment]
Hi, did you find solution for this issue?

**Comment by hoanghiephui** [comment]
Wow

**Comment by hoanghiephui** [comment]
Wow

**Comment by hoanghiephui** [comment]
Wow

**Comment by janishar** [comment]
@GoLok56 do try replace this
```kotlin
@View(R.id.sdvItemSwipeCard)
@JvmField
var ivInterest: SimpleDraweeView? = null
```
with this one 
```kotlin
@View(R.id.sdvItemSwipeCard)
lateinit var ivInterest: SimpleDraweeView
```
similarly for other views

**Comment by janishar** [comment]
What is the Android Studio version you are using? @GoLok56 
Try to invalidate cache and run

**Comment by satadii11** [comment]
it has been 1.5 years since the issue if I'm not mistaken I was using java instead of Kotlin just for this class. it solved the problem.
