### ISSUE TITLE
Disable swiping for SwipePlaceHolderView

### ISSUE THREAD

**Issue by rmsaksida** [janishar/PlaceHolderView#15]
Hey, I was wondering if the library allows us to disable swiping somehow for `SwipePlaceHolderView`? Meaning cards could only be swiped programatically.

If it doesn't, this would be a cool feature to have - something like `swipePHView.setSwipeEnabled(false)`. 

Let me know if a pull request for this would be desirable :smiley:  Thanks!

**Comment by janishar** [comment]
@rmsaksida Thanks for the nice suggestion. 
Could you help me out with use cases where this can be a requirement.

I am writing a putback mechanism for the cards. So if a card has not to be removed it could be put back and further cards can only be removed if putback is not intended. This will provide a mechanism of card swipe control like Tinder. Tinder cards let you swipe and then put it back if the heart is over. If the swipe disable feature can be used in more versatile cases please let me know.

Thanks

**Comment by rmsaksida** [comment]
Hey, I can think of a few use cases:

- The library user may be interested in the Tinder layout (a stack of cards), but not necessarily the touch swiping feature itself. Just the stack of cards is a nice UI element even if you can't swipe them.

- The app user is supposed to do something before he can swipe the cards. Maybe the cards will be "locked" for some reason before he can do it.

- A variation of the above: maybe the card is automatically swiped once the user completes a task, and he can't do it himself. (I have an use case similar to this)

- There is some dynamic content inside cards that has to be loaded before they're swiped. Maybe the card is fetching data from an API, and you want to disable swiping before the data is fetched and rendered.

So I think this feature is actually pretty different from a "card putback". The card putback is triggered _after_ swiping the card, in this case the swiping won't happen at all.

I suspect the use case for disabling swiping is actually more common than a card putback... the latter looks more niche in my opinion.

**Comment by janishar** [comment]
Okay You do it and push your changes

**Comment by rmsaksida** [comment]
Okay, I'll try to implement this and create a pull request. :+1:

**Comment by ramseth001** [comment]
@janishar I am looking for this feature. I was wondering whether this is implemented?

**Comment by ramseth001** [comment]
Sorry. Just found out swipeView.disableTouchSwipe();
