### ISSUE TITLE
consuming time for add new cards in the stack

### ISSUE THREAD

**Issue by programmerpinggiran** [janishar/PlaceHolderView#150]
Hello Janishar, 
First of all, thanks for this great library, really appreciate it.

but i have problem 
1. I have a stack of 3 cards: A, B and C added in this order.
2. When Card A removed, then B animate scale to replacing A position.
3. the process B to A position its consuming some time, so when user doing fast swipe between card, but Card B not yet to A posisiton.. so its look laggy.

what i want to achieve is how to make it fast enough.. so user can swipe faster between card.
so it will look like: user swipe card A and immediately can swipe card B.

thanks.

**Comment by janishar** [comment]
@mcsentul You are testing on which device?

**Comment by programmerpinggiran** [comment]
@janishar im using xiaomi redmi note 5pro.. 

Or this case because 2.25*animationtime inside doSwipe function?

**Comment by programmerpinggiran** [comment]
@janishar trying change animationtime, but the case still exist.

**Comment by programmerpinggiran** [comment]
I have found a solution, basicaly i was doing so much work on onSwipeHead() thats make looks laggy

thanks for great library

**Comment by janishar** [comment]
@programmerpinggiran Thanks! Closing this issue now.
