### ISSUE TITLE
Gravity issue

### ISSUE THREAD

**Issue by JEuler** [janishar/PlaceHolderView#16]
Hi! Thank you for the cool library first of all. I have a problem using it. So, I have the following code in my Relative layout. So, it is just the all screen, you know.

`<com.mindorks.placeholderview.SwipePlaceHolderView
                android:id="@+id/cards_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />`

I have the following layout for the cardview 
`<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:id="@+id/pod_card"
    android:layout_width="@dimen/card_width"
    android:layout_height="@dimen/card_height"
    card_view:cardCornerRadius="4dp"
    card_view:cardElevation="4dp"
    card_view:cardUseCompatPadding="true">`

With that layout I have the cards placed in the center of screen. That is fine, i think. But I want to place content at the bottom, with some padding. So, I write this in my Activity: 

`.setSwipeDecor(new SwipeDecor()
                        .setViewGravity(Gravity.BOTTOM)
                        .setRelativeScale(0.01f));`

Am I correct, that this should place the content at the bottom of view? I see that it is showing the cards content at the center.

**Comment by janishar** [comment]
@JEuler Thank you for your kind words.

I have fixed the issue in the 0.2.9 version.
please use this version
```groovy
compile 'com.mindorks:placeholderview:0.2.9'
```

**Comment by JEuler** [comment]
Thank you! It is now at the bottom. But I have another issue now ( sorry) ). When I drag the card, it is not dragging at all, I can only swipe it left or right, and could not drag it to the top of the screen (that was the main reason of match_parenting the view).

**Comment by JEuler** [comment]
And another update. If I set the gravity to CENTER, all is dragging well. And If I set the Gravity.BOTTOM alone or with CENTER cards are not dragging freely.

**Comment by janishar** [comment]
@JEuler Don't use gravity for this.
You will have to do few additional steps:

1. In the CardView ( or whichever is the topmost view group containing card's layout) add:

```xml
android:layout_gravity="bottom|center"
```

2. In the SwipeDecor use:
```java
 DisplayMetrics displaymetrics = new DisplayMetrics();
 getWindowManager().getDefaultDisplay().getMetrics(displaymetrics);

 <view_name>.getBuilder()
                        .setSwipeDecor(new SwipeDecor()
                             .setViewHeight(displaymetrics.heightPixels)
                             .setViewWidth(displaymetrics.widthPixels)
```

**Comment by JEuler** [comment]
Thank you so much! All is working just like I need. Great job with library!

**Comment by equilizer** [comment]
Hi, can i use VideoView widgets instead of ImageView and use swipe left and right to pause a video and start the next video at the same time ..please help
