### ISSUE TITLE
SwipePlaceHolderView

### ISSUE THREAD

**Issue by gauraviqlance** [janishar/PlaceHolderView#161]
It is not work around scroll-view or nested scroll view  to swipe direction and also not showing long view in fragment class to cut some view portion of card view items.

(Put SwipePlaceHolderView on inside the scroll view so you can understand what is happening and also check long view so it is not showing full view of card in fragment class. of bottom navigation Bar.)

**Comment by janishar** [comment]
yes scrollview feature is not built into this SwipePlaceHolderView
