### ISSUE TITLE
lifecycle

### ISSUE THREAD

**Issue by jjhesk** [janishar/PlaceHolderView#17]
There are leaks found in side of the viewholder because there is an object that has been declared in static level at the constructor. What is the proper annotation that i can declare to destroy such objects?
@janishar 
I have found.. 

```
@PreDestroy
    private void destroy() {

    }
```

**Comment by janishar** [comment]
Annotate the class with @NonReusable and it will set all the variables as null when the view is removed from the placeholder view. So GC can collect it.

Let me know if this works

**Comment by jjhesk** [comment]
not sure why there are still leaks detected from leakage library.

**Comment by janishar** [comment]
Can u post the trace of leak canary

**Comment by janishar** [comment]
@jjhesk 
Now you can use `@Recycle` for the cleanup:
https://github.com/janishar/PlaceHolderView/releases/tag/0.7.3
