### ISSUE TITLE
Swipe turn off

### ISSUE THREAD

**Issue by JEuler** [janishar/PlaceHolderView#18]
Hi! As I see in the changelog of last version you have added the possibility to turn off the swipe functionality. Unfortunately it is turning off all animations of swipe. 

I will briefly describe my case: I want user to have ability to pass through cards by clicking buttons on them. But I don't want him to have ability to swipe or drag cards. 

Is this possible using your library?

**Comment by janishar** [comment]
@JEuler Please refer version 0.5.1 release notes:
https://github.com/janishar/PlaceHolderView/releases/tag/0.5.1

It will enable you to do so.

**Comment by JEuler** [comment]
Thank you very much! It worked!
