### ISSUE TITLE
implement @LoadMore in SwipePlaceHolderView

### ISSUE THREAD

**Issue by NishantRajput** [janishar/PlaceHolderView#22]
How can I implement @LoadMore in SwipePlaceHolderView??

**Comment by janishar** [comment]
@NishantRajput You want to implement loading for the swipe views till you get more data from the api?

**Comment by NishantRajput** [comment]
Yes, I want a bunch of user to display in which page returns 20 users at time and I want to load more pages.

**Comment by janishar** [comment]
@NishantRajput Please use version 0.6.1
compile 'com.mindorks:placeholderview:0.6.1'

See the release note:
https://github.com/janishar/PlaceHolderView/releases/tag/0.6.1
```java
mSwipePlaceHolderView.addItemRemoveListener(new ItemRemovedListener() {

        @Override
        public void onItemRemoved(int count) {
            //do something when the count changes to some specific value.
            //For Example: Call server to fetch more data when count is zero
        }
    });
```

**Comment by NishantRajput** [comment]
Thanks.. Its working.
