### ISSUE TITLE
How to expand/collapse ExpandablePlaceHolderView programmatically?

### ISSUE THREAD

**Issue by aimanbaharum** [janishar/PlaceHolderView#26]
Hey guys, I want to expand all parents from a press of a button. Is there a way we can do so?

I know there is `@SingleTop` but it only expand the first parent item. 

Please advice, thanks.

**Comment by janishar** [comment]
@aimanbaharum I have added the the programmatically expand/collapse in the version 0.7.0
Refer to this release note for more details: [Release-0.7.0-Notes-Link](https://github.com/janishar/PlaceHolderView/releases/tag/0.7.0)
