### ISSUE TITLE
@Click annotation

### ISSUE THREAD

**Issue by biskit** [janishar/PlaceHolderView#3]
if i set @Click on profileImageView (from your eg) it does not receive any of onSwipe* events! 
how does one go about it?

**Comment by janishar** [comment]
The thing is that the view is architectured in a way that their is a main frame that holds all the other views provided by xml layout. And the touch listener is attached with the main frame. And the frame passes the touch event to child views if it's beyond the threshold of a click. This is done for not blocking event passing so a child view can implement onclick and other listeners. So, I don't think you can have onclick on the whole view as well as touch event processing in this architecture out of box. 
But if you really need this what you can do is to implement a on touch listener on the imageview and beyond the threshold of a click remove the listener so event is captured by the parent. Then on onSwipeCancelState reattach the touch listener to the imageview.

**Comment by biskit** [comment]
sorry for not being clear. let's take your TinderCard as example. You have @Swipe* events implemented here. what I'm asking is in the same class if I implement @Click(R.id.profileImageView) the rest of the events (@Swipe*) do not come to R.id.profileImageView. It however does come to R.id.nameAgeTxt or R.id.locationNameTxt.


my question is how do I get @Click and @Swipe* on R.id.profileImageView.

**Comment by janishar** [comment]
The profileImageView along with nameAgeTxt and locationNameTxt are child views of a frame view that is created programmatically by the library. frame has a OnTouchListener and it passes the touch event to its child views if the swipe is small. 

https://developer.android.com/training/gestures/viewgroup.html

In this case if u attach @Click to profileImageView then it will consume the touch events and the frame wont be able to process swipe. The portion beyond profileImageView is not consuming the touch events so the frame is able to process the swipe.

If you want to have @Click and @Swipe both to work in this case then you will have to do it in your implementation right now.  

A work around is to use OnTouchListener on profileImageView in place of @Click. process the click event if the touch distance is small and remove the OnTouchListener attached to profileImageView when the touch distance is more than that. And then reattach OnTouchListener to the profileImageView when onSwipeCancelState is broadcased to the TinderCard

**Comment by biskit** [comment]
thanks for explanation. makes sense. back to your TinderCard example (and as in Tinder) if I want to get details, the typical way is to click on the card. How would you implement it here?

**Comment by janishar** [comment]
he profileImageView along with nameAgeTxt and locationNameTxt are child views of a frame view that is created programmatically by the library. frame has a OnTouchListener and it passes the touch event to its child views if the swipe is small. 

https://developer.android.com/training/gestures/viewgroup.html

In this case if u attach @Click to profileImageView then it will consume the touch events and the frame wont be able to process swipe. The portion beyond profileImageView is not consuming the touch events so the frame is able to process the swipe.

If you want to have @Click and @Swipe both to work in this case then you will have to do it in your implementation right now.  

A work around is to use OnTouchListener on profileImageView in place of @Click. process the click event if the touch distance is small and remove the OnTouchListener attached to profileImageView when the touch distance is more than that. And then reattach OnTouchListener to the profileImageView when onSwipeCancelState is broadcasted to the TinderCard

**Comment by janishar** [comment]
If this is your use case let me think about it and I will get back to you.

**Comment by biskit** [comment]
Any news on update? I like everything else about it. Hope you can find a
design for it :)

**Comment by janishar** [comment]
Hey, yup I hv written an update wit  the click and swipe working together. There is a small issue I hv to solve.. the view is responding to swipe in alternate swipes n click working always. Let me solve this issue then will provide a release

**Comment by janishar** [comment]
@biskit I have fixed the library to listen to both click and swipe in version 0.1.4

**Comment by biskit** [comment]
awesome, let me pull and build. will let you know shortly! thanks a bunch
man!

**Comment by biskit** [comment]
looks great! can receive @Click and @Swipe* in my Card class. 👍 
will let you know if i face other issues!

cheers

**Comment by janishar** [comment]
@biskit please use 0.1.5

**Comment by biskit** [comment]
ok, no problem.
