### ISSUE TITLE
ImageView don't adjust to CardView's border

### ISSUE THREAD

**Issue by tupikoff** [janishar/PlaceHolderView#31]
API 19 and lower: the ImageView don't adjust to CardView's border. 
On the example of tutorial "Tinder Swipe" (just changed app:cardCornerRadius="30dp"):
API 19: https://www.dropbox.com/s/wzbjsl4ql0qr77x/Screenshot_1495827653.png?dl=0
API 24: https://www.dropbox.com/s/eidrkokvyq5me5s/Screenshot_1495827593.png?dl=0

**Comment by tupikoff** [comment]
@janishar can you help?

**Comment by janishar** [comment]
@tupikoff Sure I will test it today

**Comment by janishar** [comment]
@tupikoff This is the issue with the CardView of Android Design Support Library.
Please refer to below link to solve it: 
https://stackoverflow.com/questions/27394300/make-imageview-fit-width-of-cardview

**Comment by tupikoff** [comment]
A did it! Thanks!
I can make pull request for fix example. Are you need it @janishar?

**Comment by janishar** [comment]
@tupikoff sure you make the pull request and thanks for finding the solution. Greatly appreciated.

**Comment by tupikoff** [comment]
@janishar I made pull request https://github.com/janishar/Tutorials/pull/1
