### ISSUE TITLE
Disable particular Swipe Left/Right/Top/Bottom

### ISSUE THREAD

**Issue by hubdestro** [janishar/PlaceHolderView#32]

**Comment by janishar** [comment]
@hubdestro Currently we have 3 types of swipes: Vertical(top-bottom), Horizontal(left-right) and All Direction. 
There are flags for them:
Example:
`mSwipView.getBuilder() .setSwipeType(SwipePlaceHolderView.SWIPE_TYPE_VERTICAL)`
