### ISSUE TITLE
Swipe directions

### ISSUE THREAD

**Issue by core2root** [janishar/PlaceHolderView#39]
Hi, will you add up/down swipe directions?

**Comment by janishar** [comment]
@core2root Hi, yes I will do it but it will take sometime.

**Comment by core2root** [comment]
can you please say שנםוא how much time you talking, because i heavy use this library in project but now i have to add the up and bottom directions, and if it will take you long time i would have to search alternative library, but i really want to stay with this one.
thank you in advance.

**Comment by janishar** [comment]
@core2root Thanks, I will be able to look into it after this week.

**Comment by janishar** [comment]
Can you explain the complete use case meanwhile?

**Comment by core2root** [comment]
Hi, i am working on app that need callbacks for all direction swipes (Up,Bottom,Left,Right).

**Comment by janishar** [comment]
@core2root I have added a new class `SwipeDirectionalView` on top of `SwipePlaceHolderView` that will provide the directional callback in the version 0.7.0
Refer to this release note for more details: [Release-0.7.0-Notes-Link](https://github.com/janishar/PlaceHolderView/releases/tag/0.7.0)

**Comment by core2root** [comment]
Thank you.
