### ISSUE TITLE
Intermediate callback before @SwipeIn / @SwipeOut

### ISSUE THREAD

**Issue by biskit** [janishar/PlaceHolderView#4]
is it possible to get a callback before @SwipeIn, @SwipeOut event completes which will return a boolean. True completes the operation and False cancels the operation (ie puts the card back on the stack where it was).
you can dispatch the @SwipeIn and @SwipeOut after that.

 ie. @SwipeIn generates a @SwipeInConfirm and @SwipeIn if @SwipeInConfirm returns True.

why do I need it? I want to be able to confirm with user whether that was their intended action. If 'Yes' I return True if 'Cancel' I return False.

**Comment by janishar** [comment]
Okay what I will do is provide a putback method so the card can be put back if swiped.  The confirmation dialog could be shown when onSwipedOut or onSwipeIn is called and then if required putback can be called. I am a bit busy with my new library JPost once I m free in a day or two will work on it.

**Comment by biskit** [comment]
lets try that to see how it works. it'll be better if this intermediate action happens first before the card is shifted, but what you say may work, though a little confusing. it can be handled with some smart graying of the background.

**Comment by janishar** [comment]
@biskit Please check the putback mechanism added in 0.5.0 version
https://github.com/janishar/PlaceHolderView/releases/tag/0.5.0

Hope it solves your problem.

**Comment by biskit** [comment]
awesome 👏 I'll check it out as soon as I have to update my code. sorry for delay.
