### ISSUE TITLE
Animate undoLastSwipe

### ISSUE THREAD

**Issue by rohand** [janishar/PlaceHolderView#41]
Is there any easy way to animate the card when undoLastSwipe is called? 
Animation similar to activatePutBack.

**Comment by janishar** [comment]
@rohand I will have to look into it and will get back to you soon.

**Comment by janishar** [comment]
@rohand 
I have added the animated card when `undoLastSwipe` is called in the version 0.7.0 
Refer to this release note for more details: [Release-0.7.0-Notes-Link](https://github.com/janishar/PlaceHolderView/releases/tag/0.7.0)
