### ISSUE TITLE
Get Swipe distance

### ISSUE THREAD

**Issue by rohand** [janishar/PlaceHolderView#42]
I would like to change the background color of the card. For smooth color fading I want to set the alpha of the background color based on the distance swiped. 
Is there any way to get the swipe distance (left and right)?

I tried @Position annotation but it always seems to be returning zero.

**Comment by janishar** [comment]
@rohand I have released 0.7.0 version with `SwipeTouch` callback.
Refer to this release note for more details: [Release-0.7.0-Notes-Link](https://github.com/janishar/PlaceHolderView/releases/tag/0.7.0)

Also, find this example project that does the card alpha animation with swipe distance: [Project-Link](https://github.com/janishar/Tutorials/tree/master/tinder-swipe-top-Left-right-bottom)
