### ISSUE TITLE
swiping causes resize content

### ISSUE THREAD

**Issue by core2root** [janishar/PlaceHolderView#45]
Hi, when i swipe to any direction it cause resize of the content inside the card.

**Comment by core2root** [comment]
I think i because of scaleX,scaleY in onAnimate() function, is there are way to disable the scaling?

**Comment by janishar** [comment]
@core2root Please refer to this Article to see if it can resolve the issue.
https://medium.com/@janishar.ali/modifying-android-tinder-swipe-view-example-to-support-auto-resize-94f9c64f641e
