### ISSUE TITLE
InfinitePlaceHolderView: clear items and resetting no more to load

### ISSUE THREAD

**Issue by orikl84** [janishar/PlaceHolderView#49]
If I want to clear all the items and reset the load more, is this the right way?

`mInfinitePlaceHolderView.removeAllViews();`
`mInfinitePlaceHolderView.noMoreToLoad();`
`mInfinitePlaceHolderView.setLoadMoreResolver(new LoadMoreView(this));`

**Comment by janishar** [comment]
@orikl84 Yes It's the right way.
You can skip this though: `mInfinitePlaceHolderView.setLoadMoreResolver(new LoadMoreView(this));`

**Comment by orikl84** [comment]
But after looking in the source code I saw`noMoreToLoad` removes the scroll listener. `setLoadMoreResolver` adds it back

**Comment by janishar** [comment]
Yes you are right you do need to call `setLoadMoreResolver` Thanks
