### ISSUE TITLE
Continuation to #3

### ISSUE THREAD

**Issue by biskit** [janishar/PlaceHolderView#5]
the fixes seem to send @Click to the TinderCard class. However, the click listeners in the MainActivity.java (for eg: R.id.acceptBtn, R.id.rejectBtn) do not work any more!

I have not exactly tested with the above classes but have code that parallel's that. So, I'm guessing the issue exists here too. My code does not receive the click events for buttons sitting in the parent frame.

**Comment by janishar** [comment]
If you are using the tinderswipe example then its happening because in the demo project the frame resizes on the phone having navigation bar making the frame to come on top of the main activity bottom buttons. Provide a bottom margin to the swipeplacehoherview i suppose it will fix it

**Comment by janishar** [comment]
https://developer.android.com/training/system-ui/navigation.html

**Comment by biskit** [comment]
preliminary testing says that could be the problem. let me do a little more
before i close it.


thanks!

**Comment by biskit** [comment]
giving it a bottom margin to unhide controls solves the problem.

**Comment by janishar** [comment]
@biskit please refer this 
[Modifying Android Tinder Swipe View Example to support auto resize](https://medium.com/@janishar.ali/modifying-android-tinder-swipe-view-example-to-support-auto-resize-94f9c64f641e#.g5so6zi4s) to get a streamline solution to the card auto resizing and button overlap solution

**Comment by biskit** [comment]
awesome thanks! and a needed feature.

however, is it possible that you support compile '
com.android.support:recyclerview-v7:23.+' instead of 24+?

i'm stuck with doing everything at SDK level 23 and build level 23.0.2 at
the moment. this puts a huge upgrade on me.

thanks!

**Comment by biskit** [comment]
bit the bullet and got on with it :-) looks good man, though I had to massage the width to fit my code.
