### ISSUE TITLE
Looks like some problem with proguard.

### ISSUE THREAD

**Issue by mwshubham** [janishar/PlaceHolderView#50]
`-keepclassmembers public class com.mindorks.test.swipe.TinderCard {*;}`
Added above line to build in minified mode

**Comment by janishar** [comment]
@mwshubham 
Please add these lines in the proguard.
```groovy
  -keepattributes *Annotation*
  -keepclassmembers class ** {
    @com.mindorks.placeholderview.annotations.** <methods>;
  }
```

**Comment by janishar** [comment]
@mwshubham Did the problem got resolved?

**Comment by mwshubham** [comment]
@janishar Yeah tried this setting worked fine! Thanks
