### ISSUE TITLE
Cards Blank in release build

### ISSUE THREAD

**Issue by chitra8** [janishar/PlaceHolderView#51]
Hello, Cards are blank. Data is their and its working if i use debuggable apk but not shwoing any content in release apk

**Comment by janishar** [comment]
@chitra8 Have you added the proguard?
```groovy
-keepattributes *Annotation*
  -keepclassmembers class ** {
    @com.mindorks.placeholderview.annotations.** <methods>;
  }
```

**Comment by chitra8** [comment]
yes i added and it solved the issue
