### ISSUE TITLE
Knowing the view that was swiped

### ISSUE THREAD

**Issue by Theusfilipe** [janishar/PlaceHolderView#52]
Hello, placeHolderView is quite good but I can't for instance get the profile of the current view because I can't access it's number consistently through onItemRemoved.

Is there a way I can get the view whenever doSwipe was done?  Is it also possible to see if it received a true or false when it was called?

Gratefull
Matheus

**Comment by janishar** [comment]
@Theusfilipe 

To get the callback for the card use the below annotations.

```java
    @SwipeOut
    private void onSwipedOut(){
        Log.d("DEBUG", "onSwipedOut");
    }

    @SwipeCancelState
    private void onSwipeCancelState(){
        Log.d("DEBUG", "onSwipeCancelState");
    }

    @SwipeIn
    private void onSwipeIn(){
        Log.d("DEBUG", "onSwipedIn");
    }

    @SwipeInState
    private void onSwipeInState(){
        Log.d("DEBUG", "onSwipeInState");
    }

    @SwipeOutState
    private void onSwipeOutState(){
        Log.d("DEBUG", "onSwipeOutState");
    }
```
