### ISSUE TITLE
ExpandablePlaceHolderView in ExpandablePlaceHolderView duplicate child

### ISSUE THREAD

**Issue by tntn001** [janishar/PlaceHolderView#54]
I add view for ExpandablePlaceHolderView with child is an ExpandablePlaceHolderView. The child will duplicate every time i expand the parent. How to fix this? Thank you!

**Comment by ailtonvivaz** [comment]
Try before add views
```expandable.removeAll()
expandable.refresh```

**Comment by tntn001** [comment]
Thank you, i tried but not true.
