### ISSUE TITLE
Checkbox missing value

### ISSUE THREAD

**Issue by tntn001** [janishar/PlaceHolderView#55]
I have added checkbox in placeholderview. When i scroll, checkbox is reset to first value.

**Comment by janishar** [comment]
@tntn001 You have to initialize the values of the checkbox in OnResolve annotated method. The view is recycled when it crosses the screen and then is redrawn. When it is redrawn then it calls the method annotated with OnResolve of the View class.

**Comment by orikl84** [comment]
How do I save the state of the view before it is recycled? for ex., if the item contains an EditText

**Comment by janishar** [comment]
@orikl84 Inflate the view item with a data object. Keep updating the pre filled text of that data object using TextChangeListener on the EditText.

**Comment by janishar** [comment]
@orikl84 refer to below link for solution: 
https://github.com/janishar/PlaceHolderView/releases/tag/0.7.3

**Comment by stlwin27** [comment]
How can I make checkbox as radio button with placeholderview?
