### ISSUE TITLE
InfinitePlaceHolderView: some item doesn't display on first load

### ISSUE THREAD

**Issue by Saiga04** [janishar/PlaceHolderView#56]
In my project. I added 20 item views into an InfinitiePlaceHolder using addView method. 

At the first load, some of the item views doesn't display, some of them does. 

Scrolling up/down or calling refresh method on InfinitiePlaceHolder make missing item views appear.

I'm using Kotlin. BTW

**Comment by janishar** [comment]
@Saiga04  
"At the first load, some of the item views doesn't display, some of them does."
can you provide some code so that I can look into this?

**Comment by janishar** [comment]
Closing this now

**Comment by iamdeadman** [comment]
Facing similar issues here, when I set the visibility for some items based on the data value they disappear after scroll and when they are recreated using the resolve method. I suspect that the data from the class level variables is getting lost when the Resolve method is called after scrolling. 

For example to give you a reference - 
I have a child view for a placeholder setup list this - 

```
public TeacherTuitionQueryListCardItem(Context context, FragmentManager fragmentManager, Map<String, String> data,
                                           TeacherTuitionQueryListItemCallback callback) {
        this.mContext = context;
        this.fm = fragmentManager;
        this.mSummary = data;
        this.mCallback = callback;
    }
```

Now, in my - 

```
@Resolve
public void onResolved() {
try {
            if(mSummary.get("location") != null && !mSummary.get("location").isEmpty()) {
                tuitionLocation.setText(mSummary.get("location"));
            } else {
                tuitionLocation.setVisibility(android.view.View.GONE);
                tuitionLocationPrefix.setVisibility(android.view.View.GONE);
            }
        } catch(Exception ignored){}       
}
```

So, I suspect that the value of mSummary gets lost when Resolved method is called after scrolling out and back in

**Comment by janishar** [comment]
@iamdeadman Please check the ` location ` field. Let me know how you are storing location? Also, put a debug flag in `onResolve` to see if `mSummary`  is null or not and post me the findings.
