### ISSUE TITLE
Profile images are not showing and @drawable is unrecognizable

### ISSUE THREAD

**Issue by vikas-github** [janishar/PlaceHolderView#59]
I have implemented the tinder like stacked view everything is working perfectly but profile images are not visible. Also @drawable is not reconizable, I created vector asset for heart and cancel buttons gives error of "couldnt resolve resource".

**Comment by janishar** [comment]
@vikas-github 
Can you share the code where you are using `@drawable` because it's not  available in PlaceHolderView. 
How you added the image in the `@Resolve` annotated method?
`couldn't resolve resource` could be something to do with the vector image itself.

**Comment by vikas-github** [comment]
Thanks for the response. The drawable issue is resolved now. But the profile image is still not showing.
Here is the code in @Resolve annoted method, `Glide.with(mContext).load("http://kelompokdua.hol.es/pic/Appetizer/juice.jpg").into(profileImageView);` Just for testing purpose I'm adding image from hard-coded link string

**Comment by janishar** [comment]
@vikas-github I checked it should work. 
Take this example:
https://github.com/janishar/Tutorials/blob/master/TinderSwipe/app/src/main/java/test/mindorks/swipe/tinderswipe/TinderCard.java

Replace with:
```java
@Resolve
    private void onResolved(){
        Glide.with(mContext).load("http://kelompokdua.hol.es/pic/Appetizer/juice.jpg")
                .bitmapTransform(new RoundedCornersTransformation(mContext, Utils.dpToPx(7), 0,
                        RoundedCornersTransformation.CornerType.TOP))
                .into(profileImageView);
        nameAgeTxt.setText(mProfile.getName() + ", " + mProfile.getAge());
        locationNameTxt.setText(mProfile.getLocation());
    }
```

**Comment by vikas-github** [comment]
Thanks its working
