### ISSUE TITLE
Access the cards below

### ISSUE THREAD

**Issue by Tokimu** [janishar/PlaceHolderView#60]
Hey! I'm trying to make fragment similar to your's in the TinderSwipe tutorial but i would like to make the cards below blurred, so we can see only the main card. Is there any way to get access to cards below to make them blurred? Or to make all cards blurred but change it when card is getting top?

**Comment by janishar** [comment]
@Tokimu 
You can get the view reference through @SwipeView.
```java
@SwipeView
 private android.view.View root; 
```
But Currently API don't exist that will tell if the below card has come to the top. I will try to add this API in the next release.

**Comment by Tokimu** [comment]
Thanks for your answer! 
Can't wait for the next release then, i think it will be very useful feature :).

**Comment by janishar** [comment]
@Tokimu 
0.7.2 has added `@SwipeHead` for this purpose.
Refer release note: https://github.com/janishar/PlaceHolderView/releases/tag/0.7.2
