### ISSUE TITLE
Multiple Child

### ISSUE THREAD

**Issue by cpsarathe** [janishar/PlaceHolderView#62]
Thank you for your great library!

regarding ExpandablePlaceHolderView
how can I add different child views?

**Comment by janishar** [comment]
@cpsarathe 
Add the parent view and then add the child views. Child views can be different to each other.

```java
mExpandableView.addView(new ParentView(mContext, data));
mExpandableView.addView(new ChildView1(mContext, data));
mExpandableView.addView(new ChildView2(mContext, data));
mExpandableView.addView(new ChildView3(mContext, data));
```
