### ISSUE TITLE
Laggy 

### ISSUE THREAD

**Issue by abdullo211** [janishar/PlaceHolderView#64]
When add view more than 30-40 app laggy
Sample addviews code:
` private fun addViews(plans: ArrayList<Plan>) {
        plans.map { market -> placeHolderView.addView(PlanMarketView(context, market)) }
        showHideNoDataLayout(placeHolderView.viewResolverCount == 0)
    }
`

**Comment by janishar** [comment]
@abdullo211 Have you set the display count.
```java
mSwipView.getBuilder()
                .setDisplayViewCount(3)
```

**Comment by abdullo211** [comment]
But in placeholder view builder is no such method `setdisplayViewCount()`

**Comment by janishar** [comment]
@abdullo211 Okay I thought you are using SwipePlaceHolderView. In the case of PlaceHolderView you should apply the same strategy with that of RecyclerView. Like Cache and View Pool.

**Comment by abdullo211** [comment]
Thanks your answer, I'll try to optimize recyclerView
