### ISSUE TITLE
tinder like swipe

### ISSUE THREAD

**Issue by MalikErramli** [janishar/PlaceHolderView#66]
i implemented the tinder like swipe, however what im trying to achieve is the ability to vertically go through the user picture in the card. do you have any pointers on how to do this ? thank  u

**Comment by janishar** [comment]
@MalikErramli If you want to have only the vertical swipe then use this:

```java
mSwipView.getBuilder()
                .setSwipeType(SwipePlaceHolderView.SWIPE_TYPE_VERTICAL)
```
