### ISSUE TITLE
Adding blur effect

### ISSUE THREAD

**Issue by Tokimu** [janishar/PlaceHolderView#67]
Is it possible to add blur effect to an imageView on a Tinder card? Whenever i do it i get memory leak of blurred bitmap. I tried to use many libriaries to add blur effect or with RenderScript but always memory is leaking.

**Comment by janishar** [comment]
@Tokimu 
In the 0.7.2 @SwipeHead will allow you to do this.

Refer release note: https://github.com/janishar/PlaceHolderView/releases/tag/0.7.2

Refer project example: https://github.com/janishar/Tutorials/blob/master/TinderSwipe/app/src/main/java/test/mindorks/swipe/tinderswipe/TinderCard.java
