### ISSUE TITLE
Child Item in reverse order using ExpandablePlaceHolderView

### ISSUE THREAD

**Issue by CyberMike97** [janishar/PlaceHolderView#68]
When i add child item in ExpandablePlaceHolderView, the items are added in reverse order. I checked also my collection and is ordered.

**Comment by ltthuc1989** [comment]
i have got this issue ,too

**Comment by janishar** [comment]
@CyberMike97 @ltthuc1989 
It has been fixed in 0.7.2 release.
Refer this: https://github.com/janishar/PlaceHolderView/releases/tag/0.7.2
