### ISSUE TITLE
Use Fragment as item class

### ISSUE THREAD

**Issue by don-prog** [janishar/PlaceHolderView#69]
Hello!
I want to use `SwipePlaceHolderView` with fragment as item class(as [this class](https://github.com/janishar/PlaceHolderView#step-3-create-item-class-to-bind-and-define-view-operations)). But it seems that I can do it, but the overridden methods inherited from the `Fragment` such as `onCreate()`, `onResume()`, `onCreateView()`, are not executed when they should. 
So, can I use the fragment with working above-mentioned methods as item class?

**Comment by janishar** [comment]
@don-prog the swipeplaceholderview has not been designed to work with fragments as item views

**Comment by taha7ussein007** [comment]
@janishar i have the same issue can i use ExpandablePlaceHolderView with fragment as item class ?
