### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by rakesh1001** [janishar/PlaceHolderView#71]
how to perform the action on adapter item from the fragment ???
i have one activity and one fragment. placeholderview is place in fragment layout. And i want to click the item and inflate some layout in the activity/fragment

**Comment by janishar** [comment]
Pass a Callback(Create an interface and implement in the Activity or Fragment) instance (this of Activity or Fragment) to the ViewItem class that you are adding into the PlaceHolderView. In`@OnClick` annotated method of the ViewItem call the callback method.
