### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by devAseemSharma** [janishar/PlaceHolderView#73]
I was willing to use this library in kotlin environment, Is this possible for now?

**Comment by Saiga04** [comment]
I've already use this great lib in my Kotlin project. I think the author didn't mean to support Kotlin when he coding this lib but somehow it just works.

**Comment by AndyGOBrien** [comment]
works for me, magic

**Comment by devAseemSharma** [comment]
I was not sure that is this library is able to generate code with provided annotations without having kapt?
