### ISSUE TITLE
How Click on Child on Expandable

### ISSUE THREAD

**Issue by iman100** [janishar/PlaceHolderView#74]
how Definition OnClick or LongClick for Childs of ExpandablePlaceHolderView???

**Comment by janishar** [comment]
refer this: https://github.com/janishar/PlaceHolderView/blob/master/app/src/main/java/com/mindorks/test/gallery/ImageTypeBig.java

**Comment by ArturoHerrera** [comment]
how do you resolve that? i need to implement an onclick listener on childs items

**Comment by tsukishiroi** [comment]
Hi @janishar i need to implement an onclick on childs items  of ExpandablePlaceHolderView, how can i do that? the link you give before does not work, thans for your time
