### ISSUE TITLE
 How to set  filterable and bubbling fast scrolling

### ISSUE THREAD

**Issue by Ravi14anand** [janishar/PlaceHolderView#76]
Iam bulding a contact android app and i need filterable expandableplaceviewholder with bubble fastscrolling to be used there .how to implement it . With your expandableviewholder 

Adding 

1.fast scrolling with Alfabateical bubble example

 https://github.com/timusus/RecyclerView-FastScroll

And

2.filterable like this

https://inducesmile.com/android/android-recyclerview-filter-search-functionality-with-search-suggest

**Comment by janishar** [comment]
@Ravi14anand RecyclerView-FastScroll could not be used because it says: "You must use FastScrollRecyclerView as your base RecyclerView"

filterable in added in the todo and will be available after some time.
