### ISSUE TITLE
Add view to position

### ISSUE THREAD

**Issue by abdullo211** [janishar/PlaceHolderView#77]
Hello!
I want to add viewResolver to a specific position, but this is deprecated and not working. How to add viewResolver to position

**Comment by janishar** [comment]
You can do this using one of the below methods: `ViewResolver` is the class that is annotated with `@Layout(--)`

```java
public <T>PlaceHolderView addView(int position, T viewResolver)
public <T>PlaceHolderView addViewBefore(T resolverOld,T resolverNew )
 public <T>PlaceHolderView addViewAfter(T resolverOld,T resolverNew )
```
