### ISSUE TITLE
Pass a Fragment into DrawerMenuItem for onClick

### ISSUE THREAD

**Issue by tmillettweather** [janishar/PlaceHolderView#80]
When setting up the menu in the for the drawer. How can we send the onclick repsonse to a fragment activity.  I am able to send to another activity using Intent and the context.  But wanted to send to a fragment.

**Comment by janishar** [comment]
yes, either send the message through the LocalBroadcastManager or Pass the callback to the activity and then delegate the message from the activity to the fragment
