### ISSUE TITLE
How to get the last click position?

### ISSUE THREAD

**Issue by rakesh1001** [janishar/PlaceHolderView#85]
@Click(R.id.monthsday_txt)
    private void onClick() {
            monthsdays.setBackgroundResource(R.drawable.circle);
}
I have a calendar view .if click on day change the day background and reset the previous click day background.

**Comment by janishar** [comment]
Pass callback from the clicked View to the Activity or Fragment and hold that View's reference. When Next View is clicked then the activity will set the earlier clicked view with new background property and call notifyItemChanged of PlaceHolderView. Position of the View can be obtained using `@Position int position`
