### ISSUE TITLE
SwipeIn and SwipeOut Callbacks not working with SwipeDirectionalView.

### ISSUE THREAD

**Issue by Ilovepancake** [janishar/PlaceHolderView#86]
For some reason, the two callbacks are not running when using SwipeDirectionalView. They only seem to run when using SwipePlaceHolderView. Please fix issue.

**Comment by janishar** [comment]
@Ilovepancake These callback wont work. There are new callbacks for this view.
refer doc here: http://janishar.com/PlaceHolderView/docs/sdv-view-definition.html
