### ISSUE TITLE
Implementation for Endless Adapter be implemented?

### ISSUE THREAD

**Issue by CRUSADER1912** [janishar/PlaceHolderView#9]
The PlaceHolderView really looks promising. Is there a way we can effortlessly implement endless adapter kinda functionality. Say, I have thousands of itemsData to be displayed and I want to display them in sets of 10 at a time. I need a call back to LoadMore once I reach the last item. 
I hope you get the idea. 
Thanks

**Comment by janishar** [comment]
What do you suggest? Like it should have a callback when the scroll reaches the last item of the set and then add more item with loading spinner?

**Comment by CRUSADER1912** [comment]
Yup, exactly what you said. When the scroll reaches the last item show the loading spinner till we get next set of data. Most importantly a callback which indicates that this scenario is reached, so that we implement logic to fetch next set of data.. In most cases from Api request.

**Comment by janishar** [comment]
okay working on it

**Comment by janishar** [comment]
@CRUSADER1912 I have written InfinitePlaceHolderView class to do the loadmore style of infinite loading. use 0.2.1 version for this. Readme provides the overview and you can find the implementation example here : https://github.com/janishar/Tutorials/tree/master/InfiniteList

**Comment by CRUSADER1912** [comment]
Well that was quick...  :+1: 
I will surely give it a try.
Cheers.
