### ISSUE TITLE
When I swipe Left and Right, I want the layouts of left and right (getSwipeInMsgLayoutId()  and getSwipeOutMsgLayoutId())

### ISSUE THREAD

**Issue by saikiran143** [janishar/PlaceHolderView#90]
We are using two different layouts, for accept and reject. They have been defined statically. I want the particular inflated view of right side(setSwipeOutMsgLayoutId()) and left side(setSwipeOutMsgLayoutId()) when we swipe. So I can update textview inside inflated layout (Left and Right). 

I want update dynamically textview inside left layout and right layout while swiping. Instead of setting statically in xml.

**Comment by janishar** [comment]
@saikiran143 Will add this feature in the future release.
